
name = "xiaoli-chinese-chess"
main = "server.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

# Durable Objects bindings
[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[routes]]
pattern = "/*"
custom_domain = true
